spring:
  servlet:
    multipart:
      enabled: ${servlet.enabled}
      max-file-size: ${servlet.max-file-size}
  jpa:
    database-platform: ${jpa.database-platform}
    open-in-view: ${jpa.open-in-view}
    show-sql: ${jpa.show-sql}
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: ${jpa.hibernate.ddl-auto}
  datasource:
    url: ${jpa.url}
    username: ${jpa.username}
    password: ${jpa.password}
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      schema: resources/db/migration
  flyway:
    enabled: ${jpa.enable}

file-save-path: ${path}
