spring:
  profiles:
    active: dev
---
spring:
  application:
    name: product-service
  cloud:
    config:
      uri: http://localhost:9006
      profile: dev
      label: main
  config:
    import: optional:configserver:http://localhost:9006

