spring:
  application:
    name: product-service
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10485760
server:
  port: 8080
file-save-path: /Users/zemin.yan/Desktop/images/
