file-save-path: /Users/zemin.yan/Desktop/images/
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update
    open-in-view: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/product_db?CreateDatabaseIfNotExist=true
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      schema: resources/db/migration
  flyway:
    enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10485760

  mail:
    host: smtp.gmail.com
    port: 587
    username: josieyan123@gmail.com
    password: uvxhgfsogbplswyi
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
  hystrix:
    command:
      default:
        execution:
          isolation:
            strategy: SEMAPHORE
            thread:
              timeoutInMilliseconds: 10000


