spring:
  profiles:
    active: dev
---
spring:
  application:
    name: product-service
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:9006
      profile: ${spring.profiles.active}
      label: main
  config:
    import: optional:configserver:http://localhost:9006

